name: Validate commit message
run-name: Validate commit message
on:
  push:
    branches:
      - main
jobs:
  validate-commit-message:
    build:
      if: (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Validate commit message
        uses: tim-actions/commit-message-checker-with-regex@0.3.1
        with:
          commits: ${{ github.event.head_commit.message }}
          pattern: '^(chore|docs|feat|fix|revert): HA-[0-9]{3,4} - .+$'
          error: "The commit message is invalid." 
