name: Validate commit message
run-name: Validate commit message
on:
  push:
    branches:
      - main
jobs:
  validate-commit-message:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github
    steps:
      - name: Check commit message length
        run: |
          echo ${{ github.event.head_commit.message }}
          echo `ls -lh`
