name: Validate commit message
run-name: Validate commit message
on:
  push:
    branches:
      - main
jobs:
  validate-commit-message:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Validate commit message ${{ github.event.head_commit.message }}"
