name: Validate commit message
run-name: Validate commit message
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
jobs:
  validate-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message length
        run: |
          echo "Validate commit message ${{ github.event.head_commit.message }}"
          echo "${{ github.action_path }}"
          message=${{ github.event.head_commit.message }}
          ./_w/actions/check_length.sh "$message"
