name: Validate commit message
run-name: Validate commit message
on:
  push:
    branches:
      - main
jobs:
  validate-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message length
        run: |
          echo "Validate commit message ${{ github.event.head_commit.message }}"
          echo "GitHub Action path ${{ GITHUB_ACTION_PATH }}"
          message=${{ github.event.head_commit.message }}
          ./${ GITHUB_ACTION_PATH }/check_length.sh "$message"
