name: Validate commit message
run-name: Validate commit message
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
jobs:
  validate-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message length
        run: |
          message=${{ github.event.head_commit.message }}
          echo "Validate commit message $message"
          echo `pwd`
        shell: sh
